name = "gemini-balance-do-worker"
main = "src/index.ts"
compatibility_date = "2024-08-05"
account_id = "7dc86fe685765efbc653e0065163d225" # <-- 请将这里替换成你的 Account ID

[durable_objects]
bindings = [
  { name = "LOAD_BALANCER", class_name = "LoadBalancer" }
]

[[migrations]]
tag = "v1" # Should be unique for each migration
new_sqlite_classes = ["LoadBalancer"]

[vars]
